### ISSUE TITLE
Extend match setup page

### ISSUE THREAD

**Issue by giladwo** [orbit1690/Scouting-2019#3]
Building on #1 - we want to automate as much as possible.
Just like you can solve the equation `x + 3 = 5`, we can determine a team's driver station from its number and match number (with a little help from TBA :slightly_smiling_face:).
For now, just receive the information of which team is at which driver station from the user - by adding it to `init` and `Model`, so that we can later (in `view`) can determine which driver station is scouted from the other two inputs.

**Comment by HadarNahshon** [comment]
So basically, remove the driver station input- and determine it from a dict in the model..?

**Comment by giladwo** [comment]
Yes, that's another way of putting that :roll_eyes:
